# Generated by Django 4.0.2 on 2022-06-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='user_name',
            new_name='username',
        ),
    ]
