# Generated by Django 4.0.2 on 2022-06-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_user_name_reg_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='username',
            new_name='reg_user_name',
        ),
    ]
